version: "3.7"

services:
  nginx:
    image: silverstripe-nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
    networks:
      - common
    restart: always
    depends_on:
      - fpm
      - websockets

  fpm:
    image: silverstripe-fpm
    container_name: silverstripe-fpm
    build:
      context: .
      dockerfile: docker/php.Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    volumes:
      - ./:/var/www
    ports:
      - "9000"
    networks:
      - common
    restart: always
    depends_on:
      db:
        condition: service_healthy

  websockets:
    image: silverstripe-fpm
    container_name: websockets
    user: www-data
    command: php vendor/silverstripe/framework/cli-script.php /dev/tasks/server-ws-swoole-run flush=1
    networks:
      - common
    ports:
      - "${FORWARD_WEBSOCKETS_PORT:-6001}:6001"
#    restart: always
    volumes:
      - .:/var/www

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "${FORWARD_DB_PORT:-SS_DATABASE_PORT}:${SS_DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${SS_DATABASE_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${SS_DATABASE_NAME}"
      MYSQL_USER: "${SS_DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${SS_DATABASE_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - ./data/db:/var/lib/mysql/
    restart: always
    healthcheck:
      test: "exit 0"
    networks:
      - common

networks:
  common:
    driver: bridge
